Correct Implementation for imt
aerius-labs/indexed-merkle-tree-halo2 pull request #1
Opened 2024-09-05 04:59 UTC by 0xVikasRushi

### Circuit Changes
1. `insert_leaf` -  remove zero hash and calculating correct intermediate root

### Circuit test cases
1. Added `test_compute_merkle_root`
2. Added `test_verify_merkle_proof`
3. Added  `test_verify_non_inclusion`
4. Updated `test_insert_leaf`
5. Updated `test_test_insert_leaf_multiple_round`

### Native Rust code
1. updated new  `IndexedMerkleTree` implementation instead of zero hashes
2. updated `insert_leaf` according to spec
3. added tests for insert_leaf and merkle root calculation as well.

2024-09-11 12:57 UTC, Vishalkulkarni45 requested changes
Thanks @0xVikasRushi for the PR.  You have changed the logic of calculating the intermediate root where you calculate it by replacing the  `leaf` with the `new_low_leaf_hash` and using the same old siblings . In the next step you verify it which does't make sense to me because you have calculated the `intermediate root` inside the circuit and again you are verifying the same computation inside  circuit
The bug in the circuit is prover can provide the low leaf and its sibling of `IMT-1` and provide the new_leaf and its sibling of `IMT-2` and still the circuit will provide the prover a valid proof 
In your current logic there is no integrity between the low leaf and the new leaf to be inserted 
I suggest you to first only look at how to make changes in the calculation of the parent hash , look into the halo2-scroll how i have done it

2024-09-11 12:57 UTC, Vishalkulkarni45 commented on src/indexed_merkle_tree.rs
>      let interim_root = compute_merkle_root(
why have you replaced the `zero_leaf_hash`, `new_leaf_proof` , `new_leaf_proof_helper` with  `new_low_leaf_hash`,`low_leaf_proof`,`low_leaf_proof_helper` ? 
Can you once revisit the logic and let me know what are changes are to be made 
You need to make changes in how the parent hash is calculated using the child nodes and not in how the intermediate roots are calculated

2024-09-11 13:06 UTC, Vishalkulkarni45 requested changes

2024-09-11 13:06 UTC, Vishalkulkarni45 commented on src/indexed_merkle_tree.rs
> +        low_leaf_proof_helper,
why have you replaced the zero_leaf_hash, new_leaf_proof , new_leaf_proof_helper with new_low_leaf_hash,low_leaf_proof,low_leaf_proof_helper ?
Can you once revisit the logic and let me know what are changes are to be made
You need to make changes in how the parent hash is calculated using the child nodes and not in how the intermediate roots are calculated

2024-09-13 10:36 UTC, rahulghangas requested changes

2024-09-13 10:36 UTC, rahulghangas commented on src/indexed_merkle_tree.rs
>          is_new_leaf_largest,
Let's replace this as well. There is no need to pass `is_new_leaf_largest` as external witness. Instead we can create two (in)equalities. 
```
low_leaf.next > new_leaf
```
and 
```
low_leaf.next == 0
```

then use an `OR` gate for both

2024-09-13 13:12 UTC, Vishalkulkarni45 commented on src/indexed_merkle_tree.rs
>          is_new_leaf_largest,
@0xVikasRushi fix this also

2024-09-15 18:00 UTC, 0xVikasRushi commented on src/indexed_merkle_tree.rs
> +    ctx.constrain_equal(&condition, one);
1.  `is_new_leaf_greater` = new_leaf < low_leaf.next
2. `is_zero`  = low_leaf.next_val === 0

constrain **OR(is_zero, is_new_leaf_greater)**

2024-09-15 18:01 UTC, 0xVikasRushi commented on src/indexed_merkle_tree.rs
>          is_new_leaf_largest,
Updated [commit](https://github.com/aerius-labs/indexed-merkle-tree-halo2/pull/1/commits/67f4708319b72bcb083f581324669e2570f020f2#r1760205321)

2024-09-16 05:01 UTC, Vishalkulkarni45 approved these changes

2024-09-26 11:05 UTC, rahulghangas approved these changes

2024-09-26 11:05 UTC, merged